### ISSUE TITLE
Position of highlighted area remains static after scrolling

### ISSUE THREAD

**Issue by karandashovrz** [JetBrains/react-buddy-react#2]
![scroll-issues](https://user-images.githubusercontent.com/77386189/147552691-59844fd1-eaf1-439d-99b8-aa667f58f0e9.gif)

**Comment by karandashovrz** [comment]
Fixed in version 1.0.1

**Comment by owlet1997** [comment]
Checked using "@react-buddy/ide-devtools": "^1.0.2"
